-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.AuthPayload exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.AuthPayload
selection constructor =
    Object.selection constructor


{-| -}
token : Field (Maybe String) Api.Object.AuthPayload
token =
    Object.fieldDecoder "token" [] (Decode.string |> Decode.nullable)


{-| -}
user : SelectionSet decodesTo Api.Object.User -> Field (Maybe decodesTo) Api.Object.AuthPayload
user object =
    Object.selectionField "user" [] object (identity >> Decode.nullable)
