-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.ExerciseSubscriptionPayload exposing (..)

import Api.Enum.MutationType
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.ExerciseSubscriptionPayload
selection constructor =
    Object.selection constructor


mutation : Field Api.Enum.MutationType.MutationType Api.Object.ExerciseSubscriptionPayload
mutation =
    Object.fieldDecoder "mutation" [] Api.Enum.MutationType.decoder


node : SelectionSet decodesTo Api.Object.Exercise -> Field (Maybe decodesTo) Api.Object.ExerciseSubscriptionPayload
node object =
    Object.selectionField "node" [] object (identity >> Decode.nullable)


updatedFields : Field (Maybe (List String)) Api.Object.ExerciseSubscriptionPayload
updatedFields =
    Object.fieldDecoder "updatedFields" [] (Decode.string |> Decode.list |> Decode.nullable)


previousValues : SelectionSet decodesTo Api.Object.ExercisePreviousValues -> Field (Maybe decodesTo) Api.Object.ExerciseSubscriptionPayload
previousValues object =
    Object.selectionField "previousValues" [] object (identity >> Decode.nullable)
