-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.WordSubscriptionPayload exposing (..)

import Api.Enum.MutationType
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.WordSubscriptionPayload
selection constructor =
    Object.selection constructor


mutation : Field Api.Enum.MutationType.MutationType Api.Object.WordSubscriptionPayload
mutation =
    Object.fieldDecoder "mutation" [] Api.Enum.MutationType.decoder


node : SelectionSet decodesTo Api.Object.Word -> Field (Maybe decodesTo) Api.Object.WordSubscriptionPayload
node object =
    Object.selectionField "node" [] object (identity >> Decode.nullable)


updatedFields : Field (Maybe (List String)) Api.Object.WordSubscriptionPayload
updatedFields =
    Object.fieldDecoder "updatedFields" [] (Decode.string |> Decode.list |> Decode.nullable)


previousValues : SelectionSet decodesTo Api.Object.WordPreviousValues -> Field (Maybe decodesTo) Api.Object.WordSubscriptionPayload
previousValues object =
    Object.selectionField "previousValues" [] object (identity >> Decode.nullable)
