-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.WordEdge exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.WordEdge
selection constructor =
    Object.selection constructor


{-| The item at the end of the edge.
-}
node : SelectionSet decodesTo Api.Object.Word -> Field decodesTo Api.Object.WordEdge
node object =
    Object.selectionField "node" [] object identity


{-| A cursor for use in pagination.
-}
cursor : Field String Api.Object.WordEdge
cursor =
    Object.fieldDecoder "cursor" [] Decode.string
