-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module WatchWord.Union.PlayData exposing (..)

import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (FragmentSelectionSet(FragmentSelectionSet), SelectionSet(SelectionSet))
import Json.Decode as Decode
import WatchWord.InputObject
import WatchWord.Interface
import WatchWord.Object
import WatchWord.Scalar
import WatchWord.Union


selection : (Maybe typeSpecific -> constructor) -> List (FragmentSelectionSet typeSpecific WatchWord.Union.PlayData) -> SelectionSet constructor WatchWord.Union.PlayData
selection constructor typeSpecificDecoders =
    Object.unionSelection typeSpecificDecoders constructor


onConnectData : SelectionSet decodesTo WatchWord.Object.ConnectData -> FragmentSelectionSet decodesTo WatchWord.Union.PlayData
onConnectData (SelectionSet fields decoder) =
    FragmentSelectionSet "ConnectData" fields decoder


onFilterData : SelectionSet decodesTo WatchWord.Object.FilterData -> FragmentSelectionSet decodesTo WatchWord.Union.PlayData
onFilterData (SelectionSet fields decoder) =
    FragmentSelectionSet "FilterData" fields decoder


onIdentifyData : SelectionSet decodesTo WatchWord.Object.IdentifyData -> FragmentSelectionSet decodesTo WatchWord.Union.PlayData
onIdentifyData (SelectionSet fields decoder) =
    FragmentSelectionSet "IdentifyData" fields decoder


onMemorizeData : SelectionSet decodesTo WatchWord.Object.MemorizeData -> FragmentSelectionSet decodesTo WatchWord.Union.PlayData
onMemorizeData (SelectionSet fields decoder) =
    FragmentSelectionSet "MemorizeData" fields decoder


onOrderData : SelectionSet decodesTo WatchWord.Object.OrderData -> FragmentSelectionSet decodesTo WatchWord.Union.PlayData
onOrderData (SelectionSet fields decoder) =
    FragmentSelectionSet "OrderData" fields decoder
