-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object exposing (..)


type AuthPayload
    = AuthPayload


type Exercise
    = Exercise


type Game
    = Game


type User
    = User


type Word
    = Word
