-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Enum.ExerciseOrderByInput exposing (..)

import Json.Decode as Decode exposing (Decoder)


type ExerciseOrderByInput
    = Id_ASC
    | Id_DESC
    | Views_ASC
    | Views_DESC
    | Completed_ASC
    | Completed_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC


decoder : Decoder ExerciseOrderByInput
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "views_ASC" ->
                        Decode.succeed Views_ASC

                    "views_DESC" ->
                        Decode.succeed Views_DESC

                    "completed_ASC" ->
                        Decode.succeed Completed_ASC

                    "completed_DESC" ->
                        Decode.succeed Completed_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    _ ->
                        Decode.fail ("Invalid ExerciseOrderByInput type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : ExerciseOrderByInput -> String
toString enum =
    case enum of
        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        Views_ASC ->
            "views_ASC"

        Views_DESC ->
            "views_DESC"

        Completed_ASC ->
            "completed_ASC"

        Completed_DESC ->
            "completed_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"
