-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Enum.GameOrderByInput exposing (..)

import Json.Decode as Decode exposing (Decoder)


type GameOrderByInput
    = Id_ASC
    | Id_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC
    | Name_ASC
    | Name_DESC
    | Description_ASC
    | Description_DESC
    | Slug_ASC
    | Slug_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC


decoder : Decoder GameOrderByInput
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "name_ASC" ->
                        Decode.succeed Name_ASC

                    "name_DESC" ->
                        Decode.succeed Name_DESC

                    "description_ASC" ->
                        Decode.succeed Description_ASC

                    "description_DESC" ->
                        Decode.succeed Description_DESC

                    "slug_ASC" ->
                        Decode.succeed Slug_ASC

                    "slug_DESC" ->
                        Decode.succeed Slug_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    _ ->
                        Decode.fail ("Invalid GameOrderByInput type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : GameOrderByInput -> String
toString enum =
    case enum of
        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        Name_ASC ->
            "name_ASC"

        Name_DESC ->
            "name_DESC"

        Description_ASC ->
            "description_ASC"

        Description_DESC ->
            "description_DESC"

        Slug_ASC ->
            "slug_ASC"

        Slug_DESC ->
            "slug_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"
