-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Enum.MutationType exposing (..)

import Json.Decode as Decode exposing (Decoder)


type MutationType
    = Created
    | Updated
    | Deleted


decoder : Decoder MutationType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "CREATED" ->
                        Decode.succeed Created

                    "UPDATED" ->
                        Decode.succeed Updated

                    "DELETED" ->
                        Decode.succeed Deleted

                    _ ->
                        Decode.fail ("Invalid MutationType type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : MutationType -> String
toString enum =
    case enum of
        Created ->
            "CREATED"

        Updated ->
            "UPDATED"

        Deleted ->
            "DELETED"
