-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Enum.UserRole exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-|

  - Admin -
  - Teacher -

-}
type UserRole
    = Admin
    | Teacher


decoder : Decoder UserRole
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "Admin" ->
                        Decode.succeed Admin

                    "Teacher" ->
                        Decode.succeed Teacher

                    _ ->
                        Decode.fail ("Invalid UserRole type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : UserRole -> String
toString enum =
    case enum of
        Admin ->
            "Admin"

        Teacher ->
            "Teacher"
