-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Scalar exposing (..)


type DateTime
    = DateTime String


type Id
    = Id String
