-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Enum.WordOrderByInput exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-|

  - Id_ASC -
  - Id_DESC -
  - Word_ASC -
  - Word_DESC -
  - Group_ASC -
  - Group_DESC -
  - Beginning_ASC -
  - Beginning_DESC -
  - Ending_ASC -
  - Ending_DESC -
  - Vowel_ASC -
  - Vowel_DESC -
  - UpdatedAt_ASC -
  - UpdatedAt_DESC -
  - CreatedAt_ASC -
  - CreatedAt_DESC -

-}
type WordOrderByInput
    = Id_ASC
    | Id_DESC
    | Word_ASC
    | Word_DESC
    | Group_ASC
    | Group_DESC
    | Beginning_ASC
    | Beginning_DESC
    | Ending_ASC
    | Ending_DESC
    | Vowel_ASC
    | Vowel_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC


decoder : Decoder WordOrderByInput
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "word_ASC" ->
                        Decode.succeed Word_ASC

                    "word_DESC" ->
                        Decode.succeed Word_DESC

                    "group_ASC" ->
                        Decode.succeed Group_ASC

                    "group_DESC" ->
                        Decode.succeed Group_DESC

                    "beginning_ASC" ->
                        Decode.succeed Beginning_ASC

                    "beginning_DESC" ->
                        Decode.succeed Beginning_DESC

                    "ending_ASC" ->
                        Decode.succeed Ending_ASC

                    "ending_DESC" ->
                        Decode.succeed Ending_DESC

                    "vowel_ASC" ->
                        Decode.succeed Vowel_ASC

                    "vowel_DESC" ->
                        Decode.succeed Vowel_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    _ ->
                        Decode.fail ("Invalid WordOrderByInput type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : WordOrderByInput -> String
toString enum =
    case enum of
        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        Word_ASC ->
            "word_ASC"

        Word_DESC ->
            "word_DESC"

        Group_ASC ->
            "group_ASC"

        Group_DESC ->
            "group_DESC"

        Beginning_ASC ->
            "beginning_ASC"

        Beginning_DESC ->
            "beginning_DESC"

        Ending_ASC ->
            "ending_ASC"

        Ending_DESC ->
            "ending_DESC"

        Vowel_ASC ->
            "vowel_ASC"

        Vowel_DESC ->
            "vowel_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"
