-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module WatchWord.Object.AuthPayload exposing (..)

import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import WatchWord.InputObject
import WatchWord.Interface
import WatchWord.Object
import WatchWord.Scalar
import WatchWord.Union


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) WatchWord.Object.AuthPayload
selection constructor =
    Object.selection constructor


{-| -}
token : Field String WatchWord.Object.AuthPayload
token =
    Object.fieldDecoder "token" [] Decode.string


{-| -}
user : SelectionSet decodesTo WatchWord.Object.User -> Field decodesTo WatchWord.Object.AuthPayload
user object =
    Object.selectionField "user" [] object identity
