module Json exposing (data)


data : String
data =
    """
      {
        "words": [
          {
            "word": "run",
            "group": "un"
          },
          {
            "word": "bun",
            "group": "un"
          },
          {
            "word": "sun",
            "group": "un"
          },
          {
            "word": "fun",
            "group": "un"
          },
          {
            "word": "nun",
            "group": "un"
          },
          {
            "word": "bat",
            "group": "at"
          },
          {
            "word": "cat",
            "group": "at"
          },
          {
            "word": "hat",
            "group": "at"
          },
          {
            "word": "mat",
            "group": "at"
          },
          {
            "word": "rat",
            "group": "at"
          }
        ]
      }
  """
