-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Watchword.Object exposing (..)


type AuthPayload
    = AuthPayload


type Game
    = Game


type Pattern
    = Pattern


type Session
    = Session


type SuccessMessage
    = SuccessMessage


type User
    = User


type Word
    = Word
