-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module WatchWord.Object exposing (..)


type AuthPayload
    = AuthPayload


type ConnectData
    = ConnectData


type FilterData
    = FilterData


type Game
    = Game


type IdentifyData
    = IdentifyData


type MemorizeData
    = MemorizeData


type OrderData
    = OrderData


type Pattern
    = Pattern


type Session
    = Session


type SuccessMessage
    = SuccessMessage


type User
    = User


type Word
    = Word
