-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module WatchWord.Enum.FocusType exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-|

  - None -
  - All -
  - NoWord -

-}
type FocusType
    = None
    | All
    | NoWord


decoder : Decoder FocusType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "None" ->
                        Decode.succeed None

                    "All" ->
                        Decode.succeed All

                    "NoWord" ->
                        Decode.succeed NoWord

                    _ ->
                        Decode.fail ("Invalid FocusType type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : FocusType -> String
toString enum =
    case enum of
        None ->
            "None"

        All ->
            "All"

        NoWord ->
            "NoWord"
